config/routes.rb
Rails.application.routes.draw do
  resources :computers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/computer.rb
class Computer < ApplicationRecord
    validates :storage, :numericality => {greater_than_or_equal_to: 1024}
    validates :ram, :numericality => {greater_than_or_equal_to: 8}
    validate :is_a_power_of_two?

    private

    def is_a_power_of_two?
        ram = (self.ram.to_i).to_s 2
        ram.length.times do |x|
            if x>0
                if ram[x]=="1"
                    errors.add(:ram, "Must be a power of two")
                    break
                end
            end
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]

  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:processor, :gpu, :ram, :psu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_form.html.erb
<%= form_with(model: computer, local: true) do |form| %>
  <% if computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
        <% computer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :processor %>
    <%= form.text_field :processor %>
  </div>

  <div class="field">
    <%= form.label :gpu %>
    <%= form.text_field :gpu %>
  </div>

  <div class="field">
    <%= form.label :ram %>
    <%= form.text_field :ram %>
  </div>

  <div class="field">
    <%= form.label :psu %>
    <%= form.number_field :psu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<h1>Editing Computer</h1>

<%= render 'form', computer: @computer %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Computers</h1>

<table>
  <thead>
    <tr>
      <th>Processor</th>
      <th>Gpu</th>
      <th>Ram</th>
      <th>Psu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <td><%= computer.processor %></td>
        <td><%= computer.gpu %></td>
        <td><%= computer.ram %></td>
        <td><%= computer.psu %></td>
        <td><%= link_to 'Show', computer %></td>
        <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
        <td><%= link_to 'Destroy', computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computer', new_computer_path %>

app/views/computers/new.html.erb
<h1>New Computer</h1>

<%= render 'form', computer: @computer %>

<%= link_to 'Back', computers_path %>

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Processor:</strong>
  <%= @computer.processor %>
</p>

<p>
  <strong>Gpu:</strong>
  <%= @computer.gpu %>
</p>

<p>
  <strong>Ram:</strong>
  <%= @computer.ram %>
</p>

<p>
  <strong>Psu:</strong>
  <%= @computer.psu %>
</p>

<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AulaTestes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>